printWidth: 120 #все строки не длиннее 120 символов
trailingComma: es5 # автоматическая расстановка запятых
tabWidth: 2 # вечинина таба - 2 пробела
semi: false # без ;
singleQuote: true # одинарные кавычки ''
'endOfLine': 'lf'
